services:

  #Wordpress
  wordpress:
    image: wordpress
    container_name: wordpress_web
    restart: always
    env_file:
      - ./env/wordpress.env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariaDB
    networks:
      - nginx-net

  #MariaDB
  mariaDB:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - ./env/db.env
    networks:
      - nginx-net

  #Nginx
  nginx:
    image: nginx
    container_name: nginx-reveser-proxy
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx-net

volumes:
  wordpress:
  db:

networks:
  nginx-net: